### ISSUE TITLE
OpenSUSE tumbleweed not crawled

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/kernel-crawler#133]
**Describe the bug**

It seems like we are not crawling http://download.opensuse.org/tumbleweed/repo/oss/x86_64/

**How to reproduce it**

Check that no `kernel-default-devel` present in there is present in the output json of kernel-crawler.

**Expected behaviour**

We should be able to crawl it!

**Comment by maxgio92** [comment]
I think we can refer `/thumbleweed` (e.g. either from https://mirrors.edge.kernel.org/opensuse/thumbleweed or http://download.opensuse.org/tumbleweed)

**Comment by maxgio92** [comment]
Sorry, forget what I've written :(
It seems it doesn't change the fact.
