### ISSUE TITLE
Add support for Redhat

### ISSUE THREAD

**Issue by johnbrydon** [falcosecurity/kernel-crawler#22]
**Motivation**

I recently added Redhat support to driverkit (https://github.com/falcosecurity/driverkit/pull/165). In order to build a complete automated build pipeline, we need kernel crawler to also support redhat.

**Feature**

Similiar to driverkit, redhat will need a valid (with subscription) docker image of redhat for each version to crawl. The image name can be passed in as an argument and the distros image will retrieve all of the available kernel versions. No headers will be available but the driverkit output can be fed into driverkit with a build image to create drivers for redhat.

**Alternatives**

None available due to redhat licensing.

**Additional context**

![image](https://user-images.githubusercontent.com/31252364/176735740-7ea28a86-d15c-405f-9dce-52ab7c1d7422.png)

**Comment by FedeDP** [comment]
Fixed by #23
