### ISSUE TITLE
New Features Requests: New schema, `jsonl` output, `database` like output, crawl `research` kernels

### ISSUE THREAD

**Issue by incertum** [falcosecurity/kernel-crawler#36]
**Motivation**

Motivated by https://github.com/falcosecurity/libs/pull/524 and https://github.com/falcosecurity/libs/issues/531.

**Feature**

## Summary
Proposing the following feature enhancements for consideration to make the tool more versatile for multiple use cases.

- `[001]` - Schema update (add `dt`, `kernels`, `majorminor`, `arch` ...)
   - Saw https://github.com/falcosecurity/driverkit/issues/194, maybe just add `recommended_compiler_version` and not an image name? Building up such a knowledge base should be feasible.
- `[002]` - Add `jsonl` output format and a `database` output (one file) with new schema changes 
- `[003]` - Add `research` kernels database (sampling latest build per major minor)

---

### Schema 

Current:

```
{
  "kernelversion": 1,
  "kernelrelease": "4.9.32-15.41.amzn1.x86_64",
  "target": "amazonlinux",
  "headers": [
    "http://packages.us-east-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/Packages/kernel-devel-4.9.32-15.41.amzn1.x86_64.rpm"
  ]
}
```

Desired (something similar to this) -> translates more naturally to the concept of a database.

```
class Kernel(object):
    def __init__(self, mirror, target, kernelversion, kernelrelease, majorminor, major, minor, arch, dt, headers, kernels):
        self.mirror = mirror
        self.target = target
        self.kernelversion = kernelversion
        self.kernelrelease = kernelrelease # uname -r
        self.majorminor = majorminor
        self.major = major
        self.minor = minor
        self.arch = arch
        self.dt = dt # kernel published date
        self.headers = headers # list of header packages urls
        self.kernels = kernels # list of kernel packages urls
```

For example:

```
{
  "mirror": "https://kernel.ubuntu.com/~kernel-ppa/mainline/",
  "target": "ubuntu",
  "kernelversion": "21+21.10.1",
  "kernelrelease": "5.11.0-20-generic",
  "majorminor": "5.11",
  "major": 5,
  "minor": 11,
  "arch": "amd64",
  "dt": "2021-06-15",
  "headers": [
    "https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.22/amd64/linux-headers-5.11.0-20-generic_5.11.0-20.21+21.10.1_amd64.deb",
    "https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.22/amd64/linux-headers-5.11.0-20_5.11.0-20.21+21.10.1_all.deb"
  ],
  "kernels": [
    "https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.22/amd64/linux-image-unsigned-5.11.0-20-generic_5.11.0-20.21+21.10.1_amd64.deb",
    "https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.22/amd64/linux-modules-5.11.0-20-generic_5.11.0-20.21+21.10.1_amd64.deb"
  ]
}

{
  "mirror": "https://mirror.rcg.sfu.ca/mirror/ELRepo/kernel/el7/x86_64/RPMS/",
  "target": "el7",
  "kernelversion": "1",
  "kernelrelease": "5.19.0-1.el7.elrepo.x86_64",
  "majorminor": "5.19",
  "major": 5,
  "minor": 19,
  "arch": "x86_64",
  "dt": "2022-07-31",
  "headers": [
    "https://mirror.rcg.sfu.ca/mirror/ELRepo/kernel/el7/x86_64/RPMS/kernel-ml-devel-5.19.0-1.el7.elrepo.x86_64.rpm"
  ],
  "kernels": [
    "https://mirror.rcg.sfu.ca/mirror/ELRepo/kernel/el7/x86_64/RPMS/kernel-ml-5.19.0-1.el7.elrepo.x86_64.rpm"
  ]
}
```

### Database

Output one file per format with new schema:

```
database
├── kernels.json
└── kernels.jsonl
research
├── research_kernels.json
├── research_kernels.jsonl

```

### Research

For `dev`, `test`, `debug` and `research` scraping mirrors featuring builds for a large array of contiguous kernels can be desired (only need latest build). Would it be possible to master such capabilities into existing crawler or run a separate script in the CI to publish these `research` kernels as well? Would be much appreciated :)

See `el7` and `ubuntu` generic [example](https://github.com/falcosecurity/libs/pull/524/files#diff-10460e7718a89d9c055495ce0284906cda6be07f02adcd53896c3929ff2c2e64R35). Perhaps there are more mirrors to consider for this use case? @FedeDP

**Comment by dwindsor** [comment]
> For dev, test, debug and research scraping mirrors featuring builds for a large array of contiguous kernels can be desired (only need latest build). Would it be possible to master such capabilities into existing crawler or run a separate script in the CI to publish these research kernels as well? Would be much appreciated :)

Absolutely! We're trying to move away from supporting rich crawling features in driverkit itself, so this feature might be more appropriate for kernel-crawler. The task of crawling for headers packages is very difficult, (as you've clearly seen given your other PRs 🚀). It makes sense to contain that logic in one place, unless of course your use case prevents using kernel-crawler and driverkit in this manner?

**Comment by dwindsor** [comment]
> Desired (something similar to this) -> translates more naturally to the concept of a database.

Yes! The schema format is converging 🚀. This looks great, two things to note:

1. driverkit considers a kernel release to have these parts. From [`kernelrelease.go`](https://github.com/falcosecurity/driverkit/blob/master/pkg/kernelrelease/kernelrelease.go):

```go
type KernelRelease struct {
	Fullversion      string       `json:"full_version"`
	Version          int          `json:"version"`
	PatchLevel       int          `json:"patch_level"`
	Sublevel         int          `json:"sublevel"`
	Extraversion     string       `json:"extra_version"`
	FullExtraversion string       `json:"full_extra_version"`
	Architecture     Architecture `json:"architecture"`
}
```

👆 of course we could change this in driverkit, but it might make sense to fully tokenize your schema (opportunistically defining `PatchLevel`, `Sublevel`, `ExtraVersion` etc when appropriate).

2. We've been making changes to the schema lately, do we need to start versioning the schema? I don't think so, it should be stabilizing soon (maybe here?), but just thought I'd call it out. @FedeDP

**Comment by incertum** [comment]
> ```go
> type KernelRelease struct {
> 	Fullversion      string       `json:"full_version"`
> 	Version          int          `json:"version"`
> 	PatchLevel       int          `json:"patch_level"`
> 	Sublevel         int          `json:"sublevel"`
> 	Extraversion     string       `json:"extra_version"`
> 	FullExtraversion string       `json:"full_extra_version"`
> 	Architecture     Architecture `json:"architecture"`
> }
> ```
> 
> 👆 of course we could change this in driverkit, but it might make sense to fully tokenize your schema (opportunistically defining `PatchLevel`, `Sublevel`, `ExtraVersion` etc when appropriate).

Very nice, yes big +1.

**Comment by maxgio92** [comment]
I like these ideas! They make sense to me.

I also like the idea to distribute the schema changes, but not sure they are needed.

I agree to keep the contract in Driverkit.

**Comment by incertum** [comment]
Let's see how the `driverkit` refactor goes and then check back in if these more "nice to have" schema changes here would be ok to support. From a research and debugging point of view it could be nice to more easily SQL like search and sample from the kernel-crawler dumps.
