### ISSUE TITLE
Minkube is very verbose

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/kernel-crawler#65]
**Describe the bug**

Minikube is super verbose, counting up to 300k lines of output.

**How to reproduce it**

See latest prow output: https://prow.falco.org/view/s3/falco-prow-logs/logs/update-kernels/1589497980124139520

**Expected behaviour**

A little bit less verbose :laughing: 

/cc @alacuku

**Comment by alacuku** [comment]
Hey @FedeDP, this issue should be now solved. See #67

**Comment by FedeDP** [comment]
Oh yep! I hoped this would be autoclosed!
/close
